packages:
  # all packages in direct subdirs of packages/
  - "frontend/**/*"
  # all packages in subdirs of portfolio/
  - "backend/**/*"
  # exclude packages that are inside test directories
  - "!**/test/**"
